<html>
<head>
	<style>

	/* Generated by Font Squirrel (http://www.fontsquirrel.com) on January 16, 2011 */

	A:link {text-decoration: none; color: black;}
	A:visited {text-decoration: none; color: black;}
	A:active {text-decoration: none; color: black;}
	A:hover {text-decoration: underline; color: black;}

	html, body {
	margin: 0;
	padding: 0;

	/* get rid of that 2px window border in Internet Explorer 6 */
	border: 0;

	/* fill the height of the browser */
	height: 100%;
	}
	html {overflow-y: scroll;}

	body {
	background-image:url('images/bg.jpg');
	background-attachment:fixed;
	}

	.subheading {
	font-family: 'BlackChanceryRegular', Arial, sans-serif;
	font-size: 25pt;
	text-align:left;
	padding-top:25px;
	}

	#container {
	position:relative; /* needed for footer positioning*/
	margin:0 auto; /* center, not in IE5 */
	width:950px;

	height:auto !important; /* real browsers */
	height:100%; /* IE6: treaded as min-height*/
	min-height:100%; /* real browsers */
	background-image:url('images/sand.png');
	}

	#content {
	margin-left:50px;
	margin-right:50px;
	}


	#header {
	font-family: 'BlackChanceryRegular', Arial, sans-serif;
	font-size: 70pt;
	text-align:center;
	}

	#guidenav {
	font-family: 'BlackChanceryRegular', Arial, sans-serif;
	font-size: 25pt;
	text-align:center;
	}
	#skillnav {
	font-family: 'BlackChanceryRegular', Arial, sans-serif;
	font-size: 20pt;
	text-align:center;
	}

	#guidepage {
	font-family: 'nevisBold', Arial, sans-serif;
	font-size: 14pt;
	}

	#nav {
	font-family: 'BlackChanceryRegular', Arial, sans-serif;
	font-size: 25pt;
	text-align:center;
	}

	#about {
	font-family: 'nevisBold', Arial, sans-serif;
	font-size: 15pt;
	text-align:center;
	}

	#underslider {
	font-family: 'nevisBold', Arial, sans-serif;
	font-size: 20pt;
	text-align:center;
	}

	#slider {
	    position:relative;
	    width:800; /* Change this to your images width */
	    height:400px; /* Change this to your images height */
		margin-left: auto;
		margin-right: auto;
	}

	#slider img {
	    position:absolute;
	    top:0px;
	    left:0px;
	    display:none;
	}

	#slider a {
	    border:0;
	    display:block;
	}
	/*
	playback timings (ms):
	  LoadShardBlock: 78.616 (3)
	  esindex: 0.007
	  captures_list: 94.775
	  CDXLines.iter: 12.181 (3)
	  PetaboxLoader3.datanode: 144.913 (4)
	  exclusion.robots: 0.244
	  exclusion.robots.policy: 0.235
	  RedisCDXSource: 1.228
	  PetaboxLoader3.resolve: 17.922
	  load_resource: 253.216
	*/
</style>
	<link rel="stylesheet" href="css/nivo-slider.css" type="text/css" media="screen"/>
	<script src="js/jquery1.4.js" type="text/javascript"></script>
	<script src="js/jquery.nivo.slider.pack.js" type="text/javascript"></script>
	<script type="text/javascript">
	$(window).load(function() {
		$('#slider').nivoSlider({
			effect:'fade', //Specify sets like: 'fold,fade,sliceDown'
			slices:15,
			animSpeed:500, //Slide transition speed
			pauseTime:4000,
			startSlide:0, //Set starting Slide (0 index)
			directionNav:false, //Next & Prev
			directionNavHide:false, //Only show on hover
			controlNav:false, //1,2,3...
			controlNavThumbs:false, //Use thumbnails for Control Nav
			controlNavThumbsFromRel:false, //Use image rel for thumbs
			controlNavThumbsSearch: '.gif', //Replace this with...
			controlNavThumbsReplace: '_thumb.jpg', //...this in thumb Image src
			keyboardNav:true, //Use left & right arrows
			pauseOnHover:false, //Stop animation while hovering
			manualAdvance:false, //Force manual transitions
			captionOpacity:0.8, //Universal caption opacity
			beforeChange: function(){},
			afterChange: function(){},
			slideshowEnd: function(){}, //Triggers after all slides have been shown
			lastSlide: function(){}, //Triggers when last slide is shown
			afterLoad: function(){} //Triggers when slider has loaded
		});
	});
	</script>
</head>
<body>
<div id="container">
	<div id="content">
		<div id="header">
			Lost Shard
		</div>

		<div id="nav">
		<a href="index.php" style="text-decoration:underline;">Home</a>, <a href="/wiki/wiki.php">Guide</a>, <a href="/blog/blog.php">Updates</a>, <a href="/server/server.php">Server Info</a>, <a href="/forums/forums.php">Forum</a>, <a href="/subscription/subscription.php">Subscription</a>
		</div>
		</br>
		</br>
		<div id="slider">
			<!--<img src="images/ss1.gif" alt="" />
			<img src="images/ss2.gif" alt="" />
			<img src="images/ss3.gif" alt="" />-->
			<img src="images/image1.png" alt=""/>
			<img src="images/image2.png" alt=""/>
			<img src="images/image3.png" alt=""/>
			<img src="images/image4.png" alt=""/>
			<img src="images/image5.png" alt=""/>
			<img src="images/image6.png" alt=""/>
			<img src="images/image7.png" alt=""/>
			<img src="images/image8.png" alt=""/>
			<img src="images/image9.png" alt=""/>
			<img src="images/image10.png" alt=""/>
		</div>

		<div id="about">
		</br>
		Lost Shard is an RPG server for minecraft. It features, among other things, a gold based currency, a system of land ownership and skills and abilities that allow you to differentiate yourself from everyone else.</br>
		</br>
		</div>
		<div id="header">Returning in Summer 2019</div>
	</div>
</div>
</body>
</html>
