name: Lostshard
main: com.lostshard.lostshard.Main.Lostshard
version: 0.2
softdepend: [Citizens]
commands:
   bank:
      description: Access your bank inventory at the local bank.
      usage: /<command>
   tradegold:
      description: trade 1 gold ingot to 100gc at a bank.
      usage: /<command> (amount)
   pay:
      description: pay a player money.
      usage: /<command> (player) (amount)
   plot:
      description: Plot commands.
      usage: /<command> (subCommand)
   claim:
      description: Claim a capturepoint.
      usage: /<command>
   capturepoints:
      description: Get a list of all capturepoints and position.
      usage: /<command>
   global:
      description: Selects the global chat.
      aliases: [g]
      usage: /<command>
   shout:
      description: Selects the shout chat.
      aliases: [s]
      usage: /<command>
   local:
      description: Selects the local chat.
      aliases: [l]
      usage: /<command>
   whisper:
      description: Selects the whisper chat.
      aliases: [w]
      usage: /<command>
   p:
      description: Selects the whisper chat.
      usage: /<command>
   c:
      description: Selects the whisper chat.
      usage: /<command>
   msg:
      description: Send a private message to a player.
      aliases: [m]
      usage: /<command> (Player) (Message)
   toggleglobal:
      description: Toggle global chat.
      aliases: [toggleglobalchat]
      usage: /<command>
   togglemsg:
      description: Toggle private chat.
      aliases: [toggleprivatechat,togglemsgchat]
      usage: /<command>
   reply:
      description: Replay on a private message.
      aliases: [r]
      usage: /<command> (Message)
   stats:
      description: Output player stats.
      usage: /<command>
   who:
      description: Output player list.
      aliases: [list,players,playerlist]
      usage: /<command>
   whois:
      description: Output whois.
      usage: /<command>
   spawn:
      description: Teleports to town after 10sec have a 3 houre .
      usage: /<command>
   resetspawn:
      description: Resets your spawn.
      usage: /<command>
   rules:
      description: Output rules.
      aliases: [modt]
      usage: /<command>
   test:
      description: test.
      usage: /<command>
   admin:
      description: admin.
      usage: /<command>
   build:
      description: Change build.
      usage: /<command>
   skills:
      description: Skills.
      usage: /<command>
   clan:
      description: Clan.
      usage: /<command>
   cast:
      description: cast.
      usage: /<command>
   scrolls:
      description: cast.
      usage: /<command>
   party:
      description: cast.
      usage: /<command>
   lostshardreload:
      description: reload lostshard config.
      usage: /<command>
   tpplot:
      description: tp to a plot.
      usage: /<command>
   tpworld:
      description: tp to a world.
      usage: /<command>
   boat:
      description: spawns a boat if lvl 50 in fishing or above.
      usage: /<command>
   runebook:
      description: Displays your runebook.
      usage: /<command>
   spellbook:
      description: Displays your spellbook.
      usage: /<command>
   private:
      description: set you to private.
      usage: /<command>
   public:
      description: Set you to public.
      usage: /<command>
   bind:
      description: creates a wand.
      usage: /<command>
   unbind:
      description: removes a wand.
      usage: /<command>
   setmurders:
      description: set a players murder counts.
      usage: /<command> (player) (amount)
   kill:
      description: Kill.
      usage: /<command>
   smelt:
      description: smelt stuff.
      usage: /<command>
   repair:
      description: repair stuff.
      usage: /<command>
   enhance:
      description: enhance stuff.
      usage: /<command>
   mount:
      description: Mount horse.
      usage: /<command>
   camp:
      description: Spawns a camp.
      usage: /<command>
   track:
      description: Tracks an entity.
      usage: /<command>
   tax:
      description: Makes plots pay tax.
      usage: /<command>
   gui:
      description: toggles gui.
      usage: /<command>
   ff:
      description: toggles friendly fire.
      usage: /<command>
   inv:
      description: shows a players inventory.
      usage: /<command> (player)
   ignore:
      description: ignores a player.
      aliases: [mute]
      usage: /<command> (player)
   unignore:
      description: unignores a player.
      aliases: [unmute]
      usage: /<command> (player)
   vendor:
      description: unignores a player.
      usage: /<command>
   shop:
      description: unignores a player.
      aliases: [buy,sell,store]
      usage: /<command>
   help:
      description: displays help menu.
      usage: /<command>
   broadcast:
      description: broadcast a global title.
      usage: /<command> (message)
   dc:
      description: Dungeon chest.
      usage: /<command> (minRefill) (maxRefill)
   lottery:
      description: Commit to the lottery
      usage: /<command> (amount)
   givemoney:
      description: Gives a player money
      usage: /<command> (player) (amount)
   title:
      description: Displays all titles and allows you to use sub commands for activating title
      aliases: [titles]
      usage: /<command> (title)
   resetallskills:
      description: Resetallskills allows you to reset all your skills and increase one skill to 50
      usage: /<command> (skill)
   rest:
      description: Allows you to regain stamina faster
      usage: /<command>
   meditate:
      description: Allows you to regain mana faster
      usage: /<command>
   vanish:
      description: Allows admins to hide
      usage: /<command>
   item:
      description: Allows admins to give items with ezz
      aliases: [i]
      usage: /<command>
   speed:
      description: Allows admins to set there gamemode speed.
      usage: /<command>
   pvp:
      description: Allows ez testing of pvp
      usage: /<command>
   say:
      description: Changes the say command
      usage: /<command> (message)