name: Lostshard
main: com.lostshard.lostshard.Main.Lostshard
version: 0.01
softdepend: [Citizens]
commands:
   bank:
      description: Access your bank inventory at the local bank.
      usage: /<command>
   tradegold:
      description: trade 1 gold ingot to 100gc at a bank.
      usage: /<command> (amount)
   pay:
      description: pay a player money.
      usage: /<command> (player) (amount)
   plot:
      description: Plot commands.
      usage: /<command> (subCommand)
   claim:
      description: Claim a capturepoint.
      usage: /<command>
   capturepoints:
      description: Get a list of all capturepoints and position.
      usage: /<command>
   global:
      description: Selects the global chat.
      aliases: [g]
      usage: /<command>
   shout:
      description: Selects the shout chat.
      aliases: [s]
      usage: /<command>
   local:
      description: Selects the local chat.
      aliases: [l]
      usage: /<command>
   whisper:
      description: Selects the whisper chat.
      aliases: [w]
      usage: /<command>
   p:
      description: Selects the whisper chat.
      usage: /<command>
   c:
      description: Selects the whisper chat.
      usage: /<command>
   msg:
      description: Send a private message to a player.
      aliases: [m]
      usage: /<command> (Player) (Message)
   toggleglobalchat:
      description: Toggle global chat.
      aliases: [toggleglobal]
      usage: /<command>
   toggleprivatechat:
      description: Toggle private chat.
      aliases: [togglemsg,togglemsgchat]
      usage: /<command>
   replay:
      description: Replay on a private message.
      aliases: [r]
      usage: /<command> (Message)
   stats:
      description: Output player stats.
      usage: /<command>
   who:
      description: Output player list.
      usage: /<command>
   whois:
      description: Output whois.
      usage: /<command>
   spawn:
      description: Teleports to town after 10sec have a 3 houre .
      usage: /<command>
   resetspawn:
      description: Resets your spawn.
      usage: /<command>
   rules:
      description: Output rules.
      aliases: [modt]
      usage: /<command>
   test:
      description: Output whois.
      usage: /<command>
   admin:
      description: Output whois.
      usage: /<command>
   build:
      description: Change build.
      usage: /<command>
   skills:
      description: Skills.
      usage: /<command>
   clan:
      description: Clan.
      usage: /<command>
   cast:
      description: cast.
      usage: /<command>
   scrolls:
      description: cast.
      usage: /<command>
   party:
      description: cast.
      usage: /<command>
   lostshardreload:
      description: reload lostshard config.
      usage: /<command>
   tpplot:
      description: tp to a plot.
      usage: /<command>
   tpworld:
      description: tp to a world.
      usage: /<command>
   boat:
      description: spawns a boat if lvl 50 in fishing or above.
      usage: /<command>
   runebook:
      description: Displays your runebook.
      usage: /<command>
   spellbook:
      description: Displays your spellbook.
      usage: /<command>
   private:
      description: set you to private.
      usage: /<command>
   public:
      description: Set you to public.
      usage: /<command>
   bind:
      description: creates a wand.
      usage: /<command>
   unbind:
      description: removes a wand.
      usage: /<command>
   setmurders:
      description: set a players murder counts.
      usage: /<command> (player) (amount)
   kill:
      description: Kill.
      usage: /<command>
   smelt:
      description: smelt stuff.
      usage: /<command>
   repair:
      description: repair stuff.
      usage: /<command>